// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PresenterAi.Infrastructure.Persistence;

#nullable disable

namespace PresenterAi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PresenterAiDbContext))]
    partial class PresenterAiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ExternalLogin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("ProviderEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_email");

                    b.Property<bool>("ProviderEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("provider_email_verified");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_logins_user_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_logins_provider_subject");

                    b.ToTable("external_logins", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.Presentation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Deck")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deck");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("driver");

                    b.Property<JsonDocument>("Frontmatter")
                        .HasColumnType("jsonb")
                        .HasColumnName("frontmatter");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script");

                    b.Property<int>("SlideCount")
                        .HasColumnType("integer")
                        .HasColumnName("slide_count");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_presentations_owner_id");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_presentations_owner_id_slug");

                    b.ToTable("presentations", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.PresentationRevision", b =>
                {
                    b.Property<string>("PresentationId")
                        .HasColumnType("text")
                        .HasColumnName("presentation_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("BaseVersion")
                        .HasColumnType("integer")
                        .HasColumnName("base_version");

                    b.PrimitiveCollection<int[]>("ChangedSlides")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("changed_slides");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("RevertedFrom")
                        .HasColumnType("integer")
                        .HasColumnName("reverted_from");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.HasKey("PresentationId", "Number");

                    b.ToTable("presentation_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_presentation_revisions_source", "source IN ('import', 'live_edit', 'revert')");
                        });
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "IsRevoked")
                        .HasDatabaseName("ix_refresh_tokens_user_id_is_revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CloseReason")
                        .HasColumnType("text")
                        .HasColumnName("close_reason");

                    b.Property<string>("EndReason")
                        .HasColumnType("text")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<int?>("EstimatedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_seconds");

                    b.Property<string>("PresentationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("presentation_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Upstream")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("upstream");

                    b.Property<string>("UpstreamSessionId")
                        .HasColumnType("text")
                        .HasColumnName("upstream_session_id");

                    b.Property<bool?>("UsageConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("usage_confirmed");

                    b.Property<int>("UsageSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("usage_seconds");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId")
                        .HasDatabaseName("ix_sessions_presentation_id");

                    b.HasIndex("UserId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sessions_user_id_started_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.SessionTurn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<int?>("SlideNo")
                        .HasColumnType("integer")
                        .HasColumnName("slide_no");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_session_turns_session_id_ordinal");

                    b.ToTable("session_turns", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolOverride", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<string>("ToolName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tool_name");

                    b.Property<bool>("AlwaysAsk")
                        .HasColumnType("boolean")
                        .HasColumnName("always_ask");

                    b.HasKey("ServerId", "ToolName");

                    b.ToTable("tool_overrides", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AlwaysAsk")
                        .HasColumnType("boolean")
                        .HasColumnName("always_ask");

                    b.Property<string>("AuthKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connected_at");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("last_error_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tool_servers_owner_id_slug");

                    b.ToTable("tool_servers", null, t =>
                        {
                            t.HasCheckConstraint("ck_tool_servers_auth_kind", "auth_kind IN ('none', 'oauth', 'header')");

                            t.HasCheckConstraint("ck_tool_servers_status", "status IN ('not_connected', 'connected', 'needs_reconnect', 'error')");
                        });
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolServerCredential", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<DateTimeOffset?>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ServerId");

                    b.ToTable("tool_server_credentials", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_method");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.UserToolSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("WebSearchEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("web_search_enabled");

                    b.HasKey("UserId");

                    b.ToTable("user_tool_settings", (string)null);
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ExternalLogin", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.Presentation", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.User", "Owner")
                        .WithMany("Presentations")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.PresentationRevision", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.Presentation", "Presentation")
                        .WithMany()
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.RefreshToken", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.Session", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.Presentation", "Presentation")
                        .WithMany("Sessions")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.SessionTurn", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.Session", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolOverride", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.ToolServer", "Server")
                        .WithMany("Overrides")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolServer", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolServerCredential", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.ToolServer", "Server")
                        .WithOne("Credential")
                        .HasForeignKey("PresenterAi.Infrastructure.Persistence.Entities.ToolServerCredential", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.UserToolSettings", b =>
                {
                    b.HasOne("PresenterAi.Infrastructure.Persistence.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("PresenterAi.Infrastructure.Persistence.Entities.UserToolSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.Presentation", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.Session", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.ToolServer", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("PresenterAi.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Presentations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
