import openapiTS, { astToString } from 'openapi-typescript';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(import.meta.dir, '..');
const snapshotPath = resolve(root, 'openapi/v1.json');
const generatedPath = resolve(root, 'src/api/generated.d.ts');
const errorCodesPath = resolve(root, 'src/api/errorCodes.ts');

const args = process.argv.slice(2);
const urlIndex = args.indexOf('--url');
if (urlIndex >= 0) {
  const url = args[urlIndex + 1];
  if (!url) throw new Error('--url requires an OpenAPI document URL');
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Unable to fetch OpenAPI document: ${response.status} ${response.statusText}`);
  const document = await response.json();
  await writeFile(snapshotPath, `${JSON.stringify(document, null, 2)}\n`, 'utf8');
}

const document = JSON.parse(await readFile(snapshotPath, 'utf8')) as {
  openapi: string;
  'x-error-codes'?: Array<{ code: string; status: number; title: string }>;
};
const ast = await openapiTS(document as Parameters<typeof openapiTS>[0], { alphabetize: true });
await mkdir(resolve(root, 'src/api'), { recursive: true });
await writeFile(generatedPath, `${astToString(ast)}\n`, 'utf8');

const codes = [...(document['x-error-codes'] ?? [])].sort((a, b) => a.code.localeCompare(b.code));
const union = codes.map(({ code }) => `  | ${JSON.stringify(code)}`).join('\n');
const entries = codes
  .map(({ code, status, title }) => `  ${JSON.stringify(code)}: { status: ${status}, title: ${JSON.stringify(title)} }`)
  .join(',\n');
const source = `// Generated by scripts/generate-client.ts. Do not edit by hand.\n\nexport type ErrorCode =\n${union};\n\nexport const ERROR_CODES = {\n${entries}\n} as const satisfies Record<ErrorCode, { status: number; title: string }>;\n`;
await writeFile(errorCodesPath, source, 'utf8');
console.log(`Generated ${generatedPath} and ${errorCodesPath} from ${snapshotPath}`);
