// Generated by scripts/generate-client.ts. Do not edit by hand.

export type ErrorCode =
  | "auth.account_disabled"
  | "auth.forbidden"
  | "auth.required"
  | "auth.signup_not_allowed"
  | "auth.sso_code_used"
  | "auth.sso_provider_disabled"
  | "auth.sso_state_invalid"
  | "concurrency.conflict"
  | "deck.no_driver"
  | "deck.not_found"
  | "deck.unsupported_format"
  | "document.not_found"
  | "document.not_ready"
  | "document.too_large"
  | "generation.busy"
  | "generation.job_failed"
  | "generation.job_not_found"
  | "generation.quota_exceeded"
  | "internal.error"
  | "internal.not_implemented"
  | "model.not_allowed"
  | "model.not_found"
  | "model.retired"
  | "presentation.invalid_script"
  | "presentation.not_found"
  | "presentation.slide_count_mismatch"
  | "provider.disabled"
  | "provider.not_found"
  | "provider.test_failed"
  | "rate_limit.exceeded"
  | "session.already_running"
  | "session.quota_exceeded"
  | "session.slots_busy"
  | "session.ticket_invalid"
  | "tools_auth"
  | "tools_credential_key_changed"
  | "tools_credential_unreadable"
  | "tools_credentials_unavailable"
  | "tools_header_invalid"
  | "tools_name_invalid"
  | "tools_oauth_client_required"
  | "tools_oauth_failed"
  | "tools_oauth_invalid_grant"
  | "tools_oauth_state_invalid"
  | "tools_oauth_unsupported"
  | "tools_redirect_refused"
  | "tools_response_too_large"
  | "tools_server_limit"
  | "tools_server_not_found"
  | "tools_unreachable"
  | "tools_url_blocked"
  | "tools_url_invalid"
  | "upstream.rate_limited"
  | "upstream.rejected"
  | "upstream.unavailable"
  | "validation.failed"
  | "validation.payload_too_large"
  | "validation.unsupported_media_type";

export const ERROR_CODES = {
  "auth.account_disabled": { status: 403, title: "Account disabled" },
  "auth.forbidden": { status: 403, title: "Forbidden" },
  "auth.required": { status: 401, title: "Authentication required" },
  "auth.signup_not_allowed": { status: 403, title: "Sign-up not allowed" },
  "auth.sso_code_used": { status: 400, title: "SSO code already used" },
  "auth.sso_provider_disabled": { status: 400, title: "SSO provider disabled" },
  "auth.sso_state_invalid": { status: 400, title: "Invalid SSO state" },
  "concurrency.conflict": { status: 412, title: "Concurrency conflict" },
  "deck.no_driver": { status: 422, title: "Deck driver not found" },
  "deck.not_found": { status: 404, title: "Deck not found" },
  "deck.unsupported_format": { status: 415, title: "Unsupported deck format" },
  "document.not_found": { status: 404, title: "Document not found" },
  "document.not_ready": { status: 409, title: "Document not ready" },
  "document.too_large": { status: 413, title: "Document too large" },
  "generation.busy": { status: 409, title: "Generation busy" },
  "generation.job_failed": { status: 500, title: "Generation job failed" },
  "generation.job_not_found": { status: 404, title: "Generation job not found" },
  "generation.quota_exceeded": { status: 429, title: "Generation quota exceeded" },
  "internal.error": { status: 500, title: "Internal server error" },
  "internal.not_implemented": { status: 501, title: "Not implemented" },
  "model.not_allowed": { status: 403, title: "Model not allowed" },
  "model.not_found": { status: 404, title: "Model not found" },
  "model.retired": { status: 410, title: "Model retired" },
  "presentation.invalid_script": { status: 400, title: "Invalid presentation script" },
  "presentation.not_found": { status: 404, title: "Presentation not found" },
  "presentation.slide_count_mismatch": { status: 409, title: "Presentation slide count mismatch" },
  "provider.disabled": { status: 409, title: "Provider disabled" },
  "provider.not_found": { status: 404, title: "Provider not found" },
  "provider.test_failed": { status: 502, title: "Provider test failed" },
  "rate_limit.exceeded": { status: 429, title: "Rate limit exceeded" },
  "session.already_running": { status: 409, title: "Session already running" },
  "session.quota_exceeded": { status: 429, title: "Session quota exceeded" },
  "session.slots_busy": { status: 429, title: "Session slots busy" },
  "session.ticket_invalid": { status: 401, title: "Invalid session ticket" },
  "tools_auth": { status: 401, title: "Tool server authentication failed" },
  "tools_credential_key_changed": { status: 401, title: "Tool credential key changed" },
  "tools_credential_unreadable": { status: 401, title: "Tool credential unreadable" },
  "tools_credentials_unavailable": { status: 503, title: "Tool credentials unavailable" },
  "tools_header_invalid": { status: 400, title: "Tool header is invalid" },
  "tools_name_invalid": { status: 400, title: "Tool server name is invalid" },
  "tools_oauth_client_required": { status: 400, title: "Tool OAuth client required" },
  "tools_oauth_failed": { status: 400, title: "Tool OAuth failed" },
  "tools_oauth_invalid_grant": { status: 400, title: "Tool OAuth invalid grant" },
  "tools_oauth_state_invalid": { status: 400, title: "Tool OAuth state invalid" },
  "tools_oauth_unsupported": { status: 400, title: "Tool OAuth unsupported" },
  "tools_redirect_refused": { status: 400, title: "Tool redirect refused" },
  "tools_response_too_large": { status: 502, title: "Tool response too large" },
  "tools_server_limit": { status: 400, title: "Tool server limit reached" },
  "tools_server_not_found": { status: 404, title: "Tool server not found" },
  "tools_unreachable": { status: 502, title: "Tool server unreachable" },
  "tools_url_blocked": { status: 400, title: "Tool server URL is blocked" },
  "tools_url_invalid": { status: 400, title: "Tool server URL is invalid" },
  "upstream.rate_limited": { status: 429, title: "Upstream rate limited" },
  "upstream.rejected": { status: 502, title: "Upstream rejected request" },
  "upstream.unavailable": { status: 503, title: "Upstream unavailable" },
  "validation.failed": { status: 400, title: "Validation failed" },
  "validation.payload_too_large": { status: 413, title: "Payload too large" },
  "validation.unsupported_media_type": { status: 415, title: "Unsupported media type" }
} as const satisfies Record<ErrorCode, { status: number; title: string }>;
